version: '3'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      DB_URL: "postgresql://rafael:Printuser123@database/lokabd"

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rafael
      POSTGRES_PASSWORD: Printuser123
      POSTGRES_DB: lokabd
